### ISSUE TITLE
Title text sometimes not shown

### ISSUE THREAD

**Issue by paulusasol** [Arc676/xkcd-Viewer#11]
For some comics, the so-called title text is not shown.

This might be caused by the contained characters.

Examples:
[900: Religions](https://xkcd.com/900/) (contains ±)
[1953: The History of Unicode](https://xkcd.com/1953/) (contains emojis)

App version: 0.2
Device: Aquaris m10 FHD
OS version: 16.04 (20190528)

**Comment by Arc676** [comment]
Thank you for reporting this issue! I wasn't able to reproduce this on my Nexus 5 using either of the mentioned comics. I'm running build `2019-06-01` on the `devel` channel. It could be a font issue, but I'm not sure how likely this is.

One possible cause could be partially downloaded data. Is the comic title shown? Can you check the on-device cache? All comics and comic data JSON files are stored in `~/.cache/xkcdviewer.arc676/<comic number>` on the device. Could you check the contents of the `info.0.json` files for these two comics? You could also tap the "show JSON" button (the braces) within the app while viewing these comics, but since it does not currently have a "jump to comic" feature, I understand that this might not be a simple task. If corrupted download data is indeed the issue, try force-reloading the comic.

**Comment by paulusasol** [comment]
In the cache, the downloaded `info.0.json` contains the title text as `"alt"` and does not contain obvious errors.
In case of the mentioned comic, the correct comic title and number was shown.
I believe I pressed refresh button at least with comic 900, but it did not help.
I currently have not visited the comics again because they are too far away.

**Comment by Arc676** [comment]
I've been able to reproduce this issue with comic 1853 as well. For reference, the issue is caused by this line: `qml/Main.qml:64: URIError: malformed URI sequence`. You're right about the text encoding. It appears that the encoding used in the JSON has changed.

Before:
```
Thanks, @unicode, for ruling in our favor and sending troops to end New Hampshire's annexation. \u00f0\u009f\u0099\u008f\u00f0\u009f\u009a\u0081\u00f0\u009f\u008e\u0096\u00ef\u00b8\u008f
```

After:
```
Thanks, @unicode, for ruling in our favor and sending troops to end New Hampshire's annexation. \ud83d\ude4f\ud83d\ude81\ud83c\udf96\ufe0f
```

(Notice how the UTF encoding for the emoji is much shorter now)

The reason I wasn't able to reproduce this issue is because these were in the cache since before this change. I'll look into this.
